config/routes.rb
Testapp::Application.routes.draw do

  root :to => 'pano_portfolio#jquery_plugin'
  

  match 'pano_portfolio/jquery_plugin'
  match '/pano_portfolio/quartz_composition'
  match '/pano_portfolio/bash_script'
  match '/pano_portfolio/webgl_sample'

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pano_portfolio_controller.rb
class PanoPortfolioController < ActionController::Base
  protect_from_forgery

  respond_to do |format|
    format.html
  end

  def jquery_plugin
  end
  def quartz_composition
  end
  def bash_script
  end
  def webgl_google_sample
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, :notice => 'Post was successfully created.' }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, :notice => 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/pano_portfolio.html.haml
!!! XML
!!!
%html
  %head
    %meta{'http-equiv' => "content-type", :content => "text/html;charset=UTF-8"}
    %title#my-title
      My Portfolio
    =javascript_include_tag "application"
    =csrf_meta_tag
    =favicon_link_tag 'rails.png'
    %style
      :sass
        #my-container
          margin-left: auto
          margin-right: auto
          width: 640px
          background-color: #eee
          header
            background-color: #36c
            height: 138px
            h1
              color: white
            nav
              a
                background-color: #fa0
                &:hover
                  background-color: #fb0
          footer
            background-color: #fa0
  %body
    %div#my-container
      %header
        #my-clock= raw "&nbsp;"
        #notice=flash[:notice]
        %h1= "My Portfolio"
        %nav
          =link_to "jQuery Plugin", :action => "jquery_plugin"
          =link_to "Quartz Composition", :action => "quartz_composition"
          =link_to "bash_script", :action => "bash_script"
          =link_to "WebGL Sample", :action => "webgl_sample"

      %div(id="container" width="500px")
        = yield

        %footer
          This site is rails 3.1, ruby 1.9.2, haml, sass, coffee-script.
          %nav
            =link_to "[ Source fork at GitHub ]", "https://github.com/dkim-95112/rail-3.1-resume"

app/views/layouts/posts.html.haml
!!! XML
!!!
%html
  %head
    %meta{'http-equiv' => "content-type", :content => "text/html;charset=UTF-8"}
    %title#my-title
      pano portfolio
    =stylesheet_link_tag "posts"
    =javascript_include_tag "application"
    =csrf_meta_tag
    =favicon_link_tag 'rails.png'

  %body
    %header
      %p#my-clock= raw "&nbsp;"
      #notice=flash[:notice]

    %div(id="container" width="500px")
      = yield

      %footer
        Powered by open-source rail-3.1, ruby 1.9.2, haml, sass, coffee-script.
        %nav
          =link_to "[ Source fork at GitHub ]", "https://github.com/dkim-95112/rail-3.1-resume"

app/views/pano_portfolio/bash_script.html.haml
=link_to_function "[ friend0 ]", "$('#my-friend0').toggle()"
%section#my-friend0(style="margin-left:2em")
  %pre= File.read('./public/friend0')

=link_to_function "[ not_friend0 ]", "$('#my-not-friend0').toggle()"
%section#my-not-friend0
  %a(style="margin-left:4em" href="/not_friend0")="'not_friend0' - 3 Meg data file"

=link_to_function "[ 'leven_ctl.bash' source ]", "$('#my-leven-ctl-source').toggle()"
%section#my-leven-ctl-source(style="width:620px;overflow-x:scroll")
  %pre(style="margin-left:4em")= File.read('./public/leven_ctl.bash')

=link_to_function "[ 'leven.bash' source ]", "$('#my-leven-source').toggle()"
%section#my-leven-source
  %pre(style="margin-left:6em")= File.read('./public/leven.bash')

app/views/pano_portfolio/jquery_plugin.html.haml
=link_to_function "[ widget panel ]", "$('#my-widget-panel').toggle()"
#my-widget-panel(style="margin-bottom: 5em")
  :javascript
    $.ajax({
      url: "/assets/jquery.hover_panel.js",
      dataType: "script",
      success: function(data, textStatus, jqXHR){
        options = {
          image_srcs: (function(){
            var r = [];
            for(var i = 0; i < 17; i++){
              r.push('/images/images-' + i + '.jpeg');
            }
            return r;
          })(),
          animate: {
            over:{top:166},
            left:{top:266},
            right:{top:266},
            other:{top:0},
          }
        };
        $('#my-hover-panel').hover_panel(options);  // set it up
      }
    });
  #my-hover-panel

=link_to_function "[ widget source ]", "$('#my-widget-source').toggle()"
#my-widget-source(style="margin-left:3em;overflow:scroll;height:640px")
  %pre= File.read("app/assets/javascripts/jquery.hover_panel.js")

app/views/pano_portfolio/quartz_composition.html.haml
%style
  :sass
    #my-download a
      background-color: #fa0    
    #my-quicktime-movie
      margin-left: auto
      margin-right: auto

%section#my-interactive-quartz-composition
  #my-download
    %a(href="/my%20digital%20lexicon.qtz")="Download"
  %p="Requires MacOSX 10.4 or later"

=link_to_function "[ quicktime movie ]", "$('#my-quicktime-movie').toggle()"
%section#my-quicktime-movie
  =javascript_include_tag "http://www.apple.com/library/quicktime/scripts/ac_quicktime.js"
  =javascript_include_tag "http://www.apple.com/library/quicktime/scripts/qtp_library.js"
  =stylesheet_link_tag "http://www.apple.com/library/quicktime/stylesheets/qtp_library.css"
  :javascript
    //QT_WriteOBJECT('/my%20automator.mov', '320', '256','','controller','true','autoplay','true','showlogo','true','cache','false');
    QT_WritePoster_XHTML('Click to Play', '/my%20automator-poster.png',
      '/my%20automator.mov',
      '620', '256', '',
      'controller', 'true',
      'autoplay', 'true',
      'emb#bgcolor', 'black',
      'scale', 'aspect',
      'align', 'middle');

%style
  :sass
    #my-still-images img
      width: 620px
      height: 256px
=link_to_function "[ still images ]", "$('#my-still-images').toggle()"
%section#my-still-images
  %image(src="/ots%20way.0-9.png")/
  %image(src="/ots%20way.u-z.png")/
  %image(src="/ots%20way.k-t.png")/
  %image(src="/ots%20way.a-j.png")/

=link_to_function "[ Quartz Composer Snapshots ]", "$('#my-quartz-composer-snapshots').toggle()"
%section#my-quartz-composer-snapshots(style="overflow-x:scroll")
  %image(src="/qc%20key%20queues.png")/

app/views/pano_portfolio/webgl_sample.html.haml
=link_to_function "[ Google o3d-WebGL sample ]", "$('#my-google-o3d-sample').toggle()"
%section#my-google-o3d-sample
  WebGL is supported on Firefox, Safari, Chrome, and Opera.
  =link_to "[ See khronos Wiki ]", "http://www.khronos.org/webgl/wiki/Getting_a_WebGL_Implementation"

  =javascript_include_tag 'o3d-webgl/base.js', 'o3djs/base.js', 'zsorting.js'
  #o3d(style="width:620px;height:320px")

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.haml
%a(href= "#{current_page?(post) ? posts_path : url_for(post)}")
  %div.back= "#{current_page?(post) ? '[ Back ]' : ''}"
  %div.post(id= "post_#{post.id}")
    %h1.title= post.title
    .body= simple_format h(post.body)

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.haml
#my-post-index= render :partial => @posts

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.haml
#my-post
  =render :partial => @post

  =render :file => {1 => "./jquery_plugin", 2 =>"./ots_way", 3 => "./leven" , 4 =>"./zsorting"}[@post.id]

=link_to "[ Back ]", posts_path